package main.nave.base;

//ES UN ENUM, QUE CONTIENE COMO ARRAY DE TIPOS DE ATAQUE, EL DE POR DEFECTO ES EL NORMAL (SIN ESPECIAL) ==>

public enum TipoAtaqueEnum {
    R_AEREO, A_CRUZ, INMERSION, B_ZONA, D_DOBLE, DEFECTO
}
